//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Properties.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có bản ghi bị lỗi, không thể thực hiện xóa hàng loạt..
        /// </summary>
        public static string Cannot_Delete_All {
            get {
                return ResourceManager.GetString("Cannot_Delete_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} chỉ chứa chữ số..
        /// </summary>
        public static string Contain_Numbers_Only {
            get {
                return ResourceManager.GetString("Contain_Numbers_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhập vào đã bị trùng..
        /// </summary>
        public static string Duplicate_Code {
            get {
                return ResourceManager.GetString("Duplicate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vạch {0} đã có trong hệ thống. Vui lòng kiểm tra lại.
        /// </summary>
        public static string Duplicate_ProductCode {
            get {
                return ResourceManager.GetString("Duplicate_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng hóa {0} đã có trong hệ thống. Vui lòng kiểm tra lại.
        /// </summary>
        public static string Duplicate_ProductGroupName {
            get {
                return ResourceManager.GetString("Duplicate_ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã SKU {0} đã có trong hệ thống. Vui lòng kiểm tra lại.
        /// </summary>
        public static string Duplicate_SKUCode {
            get {
                return ResourceManager.GetString("Duplicate_SKUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính {0} đã có trong hệ thống. Vui lòng kiểm tra lại.
        /// </summary>
        public static string Duplicate_UnitName {
            get {
                return ResourceManager.GetString("Duplicate_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được phép để trống..
        /// </summary>
        public static string Empty_Field {
            get {
                return ResourceManager.GetString("Empty_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! Vui lòng liên hệ MISA..
        /// </summary>
        public static string Error_Message_UserVN {
            get {
                return ResourceManager.GetString("Error_Message_UserVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn 1 tệp excel rồi tiếp tục..
        /// </summary>
        public static string Form_File_IsNot_Null {
            get {
                return ResourceManager.GetString("Form_File_IsNot_Null", resourceCulture);
            }
        }
    }
}
